"""
Isolated Subprocess Observation Engine for CRIMENET (Slice 7).
Enforces process boundary isolation around native C forensic extensions.
Guarantees timeout controls, clean crash containment, and safe EvidenceContract_v1 acquisition.
"""

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Tuple, Dict, Any, Optional

from src.processing.engine import ObservationEngine


class IsolatedObservationEngine(ObservationEngine):
    """
    Subprocess-isolated wrapper for forensic observation.
    Executes forensic image parsing in a standalone OS worker process, protecting
    the parent application against native C segfaults, memory leaks, and CPU lockups.
    """

    def __init__(
        self,
        timeout_seconds: int = 60,
        max_artifacts: int = 25,
        max_file_size: int = 50 * 1024 * 1024,
        python_executable: Optional[str] = None
    ):
        self.timeout_seconds = timeout_seconds
        self.max_artifacts = max_artifacts
        self.max_file_size = max_file_size
        self.python_executable = (
            python_executable
            or os.environ.get("CRIMENET_WORKER_PYTHON")
            or sys.executable
        )

    def get_engine_name(self) -> str:
        return "CRIMENET_ISOLATED_E01_ENGINE"

    def get_engine_version(self) -> str:
        return "1.0.0"

    def process(
        self,
        image_path: Path,
        output_dir: Path,
        case_id: str,
        evidence_id: str,
        job_id: str
    ) -> Tuple[Dict[str, Any], Optional[str]]:
        image_path = Path(image_path).resolve()
        output_dir = Path(output_dir).resolve()
        output_dir.mkdir(parents=True, exist_ok=True)

        contract_file = output_dir / f"evidence_contract_{job_id}.json"

        # Construct worker subprocess command
        cmd = [
            self.python_executable,
            "-m",
            "src.observation.worker",
            "--image-path", str(image_path),
            "--output-dir", str(output_dir),
            "--case-id", case_id,
            "--evidence-id", evidence_id,
            "--job-id", job_id,
            "--max-artifacts", str(self.max_artifacts),
            "--max-file-size", str(self.max_file_size)
        ]

        # Execute worker in separate process with hard timeout
        try:
            completed_proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self.timeout_seconds,
                check=False
            )
        except subprocess.TimeoutExpired as exc:
            # Clean up partial artifacts if needed
            raise TimeoutError(
                f"WORKER TIMEOUT: Observation worker exceeded maximum runtime limit of {self.timeout_seconds} seconds."
            ) from exc

        # Check worker exit code
        if completed_proc.returncode != 0:
            error_details = completed_proc.stderr.strip()
            # Try parsing structured error JSON
            try:
                err_json = json.loads(error_details)
                error_msg = f"{err_json.get('error_type')}: {err_json.get('error_message')}"
            except Exception:
                error_msg = error_details or f"Worker process crashed with exit code {completed_proc.returncode}"

            raise RuntimeError(f"WORKER FAILURE: {error_msg}")

        # Worker completed successfully - verify contract JSON was written
        if not contract_file.exists():
            raise FileNotFoundError(f"Contract output not generated by worker: '{contract_file}'")

        with open(contract_file, "r", encoding="utf-8") as f:
            contract_v1 = json.load(f)

        observed_filesystem = contract_v1.get("source_evidence", {}).get("observed_filesystem", "UNKNOWN")

        return contract_v1, observed_filesystem
